#### 自定义层
构造一个没有任何参数的自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):  # 层也是Module的自雷
    def __init__(self):
        super().__init__()
    
    def forward(self,X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

#### 将层作为组件合并到构建更复杂的模型中

In [3]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

Y = net(torch.rand(4,8))
Y.mean()   # mean值应该为0，但是在计算机中是接近0的数字

tensor(6.5193e-09, grad_fn=<MeanBackward0>)

#### 带参数的图层

In [5]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self,X):
        linear = torch.matmul(X,self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[-0.4659, -0.4069, -1.9646],
        [ 0.3837,  0.9113, -0.0144],
        [ 2.0438, -0.1133, -0.8886],
        [ 0.1443,  0.2245, -0.4618],
        [ 1.4021, -1.6358, -0.0222]], requires_grad=True)

#### 使用自定义层直接执行正向传播计算

In [6]:
dense(torch.rand(2,5))

tensor([[3.2379, 0.1410, 0.0000],
        [2.5202, 0.6697, 0.0000]])

#### 使自定义层构建模型

In [7]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.],
        [0.]])