#### 加载和保存张量

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x,'x-file')

x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

##### 存储一个张量列表，加载进内存

In [3]:
y = torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2 = torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

#### 写入或读取从字符串映射到张量的字典

In [4]:
mydict = {'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2=torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

##### 加载和保存模型参数

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)
    
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)

##### 将模型参数存在一个叫做“mlp.params”的文件

In [6]:
torch.save(net.state_dict(),'mlp.params')

##### 实例化原始多层感知机模型的一个备份。直接读取文件中存储的参数

In [7]:
clone = MLP()                                    # 先定义一个网络
clone.load_state_dict(torch.load("mlp.params"))  # 拿出参数字典
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone = clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])